---
title: "Szczepienia"
author: "Szymon Lisowski"
date: "7/12/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/mr.fox/Github/COVID_wg_powiatow/Raw_data/danehistorycznepowiaty_szczepienia/")
```

## Loading necessary packages

```{r}
library(plyr)
library(dplyr)
library(readr)
library(tidyverse)
library(purrr)
library(downloader)
```

## Pobieranie danych historycznych dla szczepień

```{r}
url <- "https://arcgis.com/sharing/rest/content/items/b860f2797f7f4da789cb6fccf6bd5bc7/data"

download(url, dest="/Users/mr.fox/Github/COVID_wg_powiatow/Raw_data/danehistorycznepowiaty_szczepienia/dataset.zip", mode="wb") 
unzip ("/Users/mr.fox/Github/COVID_wg_powiatow/Raw_data/danehistorycznepowiaty_szczepienia/dataset.zip", exdir = "./")

files_1 <- list.files(path = "/Users/mr.fox/Github/COVID_wg_powiatow/Raw_data/danehistorycznepowiaty_szczepienia", pattern = "rcb_pow_szczepienia.csv")
```

## Wczytywanie danych historycznych dla szczepień

``` {r}
df_no_date <- ldply(.data = files_1, .fun = function(i) {read.csv(i, header = TRUE, sep = ";", dec = ",", stringsAsFactors = FALSE, na.strings = c("", "NA")) })

model <- read.csv("/Users/mr.fox/Github/COVID_wg_powiatow/Raw_data/model.csv") %>% select(-1)

df_no_date_cor <- model %>%
  right_join(df_no_date, by =  "teryt") %>%
  select(-c(4:5)) %>%
  filter(teryt != "t00") %>%
  dplyr::mutate(across(everything(), ~ifelse(is.na(.), 0, .)),
    liczba_szczepien_ogolem = liczba_szczepien_ogolem + liczba_szczepien_ogolnie) %>%
  dplyr::rename(wojewodztwo = wojewodztwo.x, 
                powiat_miasto = powiat_miasto.x) %>%
  select(-liczba_szczepien_ogolnie)

date_column <- data_frame(stan_rekordu_na = rep(seq.Date(as.Date("2021-01-13"), as.Date("2022-05-19"), by = "day"), 381)) 

df_date <- cbind(df_no_date_cor, date_column)

write.csv(df_date, "/Users/mr.fox/Github/COVID_wg_powiatow/Processed_data/szczepienia.csv")
```

## Wczytywanie szczegółowych danych historycznych szczepień dla powiatów oraz gmin.

```{r}
# I chose 390th line as this is where I found the data for counties. It is not perfect solution as any changes will break the whole code chunk. I decided to use it nevertheless as the data seems to be no longer updated after the 20th of March 2022.
page = readLines("https://www.gov.pl/web/szczepienia-gmin/sprawdz-poziom-wyszczepienia-mieszkancow-gmin")[390]
page = paste(page, collapse = "")

# In this part I clean the data from the page and take only those strings that I need.
page_1 <- gsub(x = page, '"', "") 
page_1 <- sub(x = page_1, ".*w1_60_69;w1_70plus", "") 
page_1 <- sub(x = page_1, ",fileName:.*", "")
page_1 <- gsub(x  = page_1, "[\\]r[\\]n", ";")
page_1 <- gsub(x  = page_1, ",", ".")

# Now is the time to data into one table doing some more cleaning 
page_df <- tibble(df = unlist(str_split(page_1, pattern = ";"))) %>% filter(df != ":") %>% filter(!row_number() %in% c(1, last(row_number()))) 

to <- nrow(page_df)

#  There must be a faster way of dealing with this data but I found this approach to be the most intuitive for me.
wojewodztwo_nazwa <- page_df %>% filter(row_number() %in% seq(1,to, by = 13)) 
powiat_nazwa <- page_df %>% filter(row_number() %in% seq(2,to, by = 13)) 
gmina_nazwa <- page_df %>% filter(row_number() %in% seq(3,to, by = 13)) 
zaszczepieni_pelna_dawka <- page_df %>% filter(row_number() %in% seq(4,to, by = 13)) 
przyrost_zaszczepionych_od_2021_08_01 <- page_df %>% filter(row_number() %in% seq(5,to, by = 13))
liczba_ludnosci <- page_df %>% filter(row_number() %in% seq(6,to, by = 13)) 
zaszczepieni_pacjenci_jedna_dawka <- page_df %>% filter(row_number() %in% seq(7,to, by = 13)) 
zaszczepieni_pelna_dawka <- page_df %>% filter(row_number() %in% seq(8,to, by = 13)) 
grupa_wiekowa_12_19 <- page_df %>% filter(row_number() %in% seq(9,to, by = 13)) 
grupa_wiekowa_20_39 <- page_df %>% filter(row_number() %in% seq(10,to, by = 13)) 
grupa_wiekowa_40_59 <- page_df %>% filter(row_number() %in% seq(11,to, by = 13)) 
grupa_wiekowa_60_69 <- page_df %>% filter(row_number() %in% seq(12,to, by = 13)) 
grupa_wiekowa_70_plus <- page_df %>% filter(row_number() %in% seq(13,to, by = 13)) 

df <- bind_cols(wojewodztwo_nazwa, powiat_nazwa, gmina_nazwa, zaszczepieni_pelna_dawka, przyrost_zaszczepionych_od_2021_08_01, liczba_ludnosci, zaszczepieni_pacjenci_jedna_dawka, zaszczepieni_pelna_dawka, grupa_wiekowa_12_19, grupa_wiekowa_20_39, grupa_wiekowa_40_59, grupa_wiekowa_60_69, grupa_wiekowa_70_plus)

# Adding the correct names for columns
colnames(df) <- c("wojewodztwo_nazwa", "powiat_nazwa", "gmina_nazwa", "zaszczepieni_pelna_dawka", "przyrost_zaszczepionych_od_2021_08_01", "liczba_ludnosci", "zaszczepieni_pacjenci_jedna_dawka", "zaszczepieni_pelna_dawka", "grupa_wiekowa_12_19", "grupa_wiekowa_20_39", "grupa_wiekowa_40_59", "grupa_wiekowa_60_69", "grupa_wiekowa_70_plus")

# Sorting by name and adding a date. This date was chosen according to data found on source page. According to it the data is no longer updated after the 20th of March 2022.
df <- df %>% arrange(wojewodztwo_nazwa, powiat_nazwa, gmina_nazwa) %>% mutate(stan_rekordu_na = as.Date("2022-03-20"))

# The data is now ready to be worked on
write_csv(df, "/Users/mr.fox/Github/COVID_wg_powiatow/Processed_data/szczepienia_wg_gmin.csv")
```